# Generated by Django 2.0.6 on 2018-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureinfo',
            name='accessToken',
            field=models.CharField(max_length=255),
        ),
    ]
