# Generated by Django 2.0.6 on 2018-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iosapp', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(default=-1),
        ),
    ]
