# Generated by Django 2.0.6 on 2018-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iosapp', '0004_userinfo_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
            ],
        ),
    ]
