# Generated by Django 2.0.6 on 2018-06-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iosapp', '0007_commentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentInfo',
        ),
    ]
